- name: Install cURL
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Downloading Metasploit Framework
  get_url:
    url: https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb
    dest: /root/msfinstall

- name: Chmod 755 Metasploit Framework installer
  file:
    path: /root/msfinstall
    mode: 0755

- name: Install Metasploit Framework
  shell: /root/msfinstall

- name: Remove Metasploit Framework installer
  file:
    path: /root/msfinstall
    state: absent
