- name: Install Gobuster
  apt:
    name: gobuster
    state: present
    update_cache: yes

- name: Install Firefox
  apt:
    name: firefox
    state: present
    update_cache: yes

- name: Install nmap
  apt:
    name: nmap
    state: present
    update_cache: yes

- name: Install docker
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - docker
    - docker.io
    - docker-compose

- name: Disable Docker autostart
  systemd:
    name: docker
    enabled: no
    state: stopped

- name: Add docker group
  group:
    name: docker
  ignore_errors: yes

- name: Add user to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
  ignore_errors: yes

- name: Install netcat
  apt:
    name: ncat
    state: present
    update_cache: yes

- name: Install zsh
  apt:
    name: zsh
    state: present

- name: Clone oh-my-zsh
  become: no
  tags: zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "~/.oh-my-zsh"

- name: Create new zshrc
  become: no
  tags: zsh
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
    remote_src: yes

- name: Set up proper zsh theme
  become: no
  tags: zsh
  lineinfile:
    line: 'ZSH_THEME="ys"'
    path: ~/.zshrc
    regexp: '^ZSH_THEME.*'

- name: Change default shell to ZSH (reboot needed)
  tags: zsh
  shell:
    cmd: "chsh -s /usr/bin/zsh {{ user }}"

- name: Add shared folders mounting alias to zshrc
  tags: ms
  become: no
  lineinfile:
    line: "alias ms='sudo umount /mnt/hgfs/ &>/dev/null; sudo vmhgfs-fuse .host:/ /mnt/hgfs/ -o allow_other -o uid=1000 2>/dev/null'"
    path: ~/.zshrc

- name: Install openvpn
  tags: openvpn
  apt:
    name: openvpn
    state: present
    update_cache: yes

- name: Install sublime 3
  tags: subl
  shell:
    cmd: "{{ item }}"
  with_items:
    - wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
    - echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
    - apt-get update -y
    - apt-get install sublime-text

- name: Download Burp Suite Community Edition installator
  get_url:
    url: https://portswigger.net/burp/releases/download?product=community&version=2020.4&type=Linux
    dest: /root/burp.sh

- name: Chmod 755 Burp Suite Community Edition installator
  file:
    path: /root/burp.sh
    mode: 0755

- name: Install Burp Suite Community Edition
  shell: /root/burp.sh -q

- name: Remove  Burp Suite Community Edition installer
  file:
    path: /root/burp.sh
    state: absent


- name: Clone exploitdb (searchsploit)
  git:
    repo: https://github.com/offensive-security/exploitdb.git
    dest: /opt/exploit-database

- name: Link searchsploit
  file:
    path: /usr/local/bin/searchsploit
    src: /opt/exploit-database/searchsploit
    state: link
    force: yes

- name: Copy searchsploit_rc
  copy:
    dest: ~/.searchsploit_rc
    src: /opt/exploit-database/.searchsploit_rc
    remote_src: yes
